from __future__ import annotations

from pathlib import Path


_HTML_TEMPLATE = Path(__file__).with_name("veil_review_template.html").read_text(encoding="utf-8")


_HTML_UI_EN: dict[str, str] = {
    "lang": "en",
    "title": "VEIL - Vocabulary Rules",
    "search_placeholder": "Search terms...",
    "instruction": "Use Draft Capture to investigate undefined wording. Click a preview line to load the registration form, then copy a registration request for chat-side registration. Existing rows still support one-line copy and delete-command copy.",
    "capture_title": "Draft Capture",
    "capture_description": "Paste source text here to get a local undefined-wording preview. This favors conversation-local labels over specialist terminology.",
    "capture_placeholder": "Paste text to analyze...",
    "capture_btn": "Analyze Draft",
    "capture_copy_output_btn": "Copy Draft Output",
    "capture_copy_output_copied": "Draft output copied.",
    "capture_copy_prompt_btn": "Copy AI Prompt",
    "capture_copy_prompt_copied": "AI prompt copied.",
    "capture_result_title": "Draft Output",
    "capture_empty": "Paste text and run analysis.",
    "capture_none": "No preview candidates.",
    "capture_note": "This is a local preview for undefined wording. Use Copy AI Prompt when you want a better judgment from the chat model.",
    "capture_ready": "Draft preview generated. Click a line to load it into the registration form.",
    "capture_loaded": "'{term}' loaded into the registration form. It is not registered yet.",
    "capture_current_label": " (current)",
    "capture_candidate1_label": " (candidate 1)",
    "capture_candidate2_label": " (candidate 2)",
    "capture_footer": "This is the current local draft preview. Copy AI Prompt if you want a chat-side review.",
    "capture_keep_current": "keep current",
    "capture_prompt_header": "Use veil-capture semantics on the following text only. Return veil-capture style output.",
    "register_title": "Register a new rule",
    "field_term": "Term",
    "field_preferred": "Preferred",
    "field_alt2": "Candidate 2",
    "field_alt3": "Candidate 3",
    "register_term_placeholder": "e.g. current state",
    "register_preferred_placeholder": "e.g. present state",
    "register_alt2_placeholder": "Optional alternative",
    "register_alt3_placeholder": "Optional alternative",
    "register_btn": "Copy Registration Request",
    "register_commands_btn": "Copy Commands",
    "register_missing": "Term and preferred form are required.",
    "register_copied": "Registration request copied.",
    "register_commands_copied": "Registration commands copied.",
    "col_term": "Term",
    "col_preferred": "Preferred (candidate 1)",
    "col_alt2": "Candidate 2",
    "col_alt3": "Candidate 3",
    "col_actions": "Actions",
    "copy_btn": "Copy",
    "delete_btn": "Delete",
    "copy_done": "Copied",
    "copy_manual": "Clipboard access is unavailable. Copy this text manually:",
    "copy_manual_done": "Manual copy prompt opened.",
    "copy_failed": "Copy failed. Copy the text manually from the prompt.",
    "count_registered": "{n} terms registered",
    "count_matching": "{n} terms matching",
    "copy_instruction": "Change '{term}' to '{candidate}'",
    "delete_instruction_header": "Run these commands to delete this rule:",
    "delete_copied": "Deletion commands copied.",
    "register_instruction_header": "Run these commands to register this rule:",
    "register_prompt_header": "Register this VEIL rule in the current repository:",
    "register_prompt_footer": "Update the SQLite canonical, then regenerate the mirror and veil.html.",
}

_HTML_UI_JA: dict[str, str] = {
    "lang": "ja",
    "title": "VEIL - 語彙ルール",
    "search_placeholder": "用語を検索...",
    "instruction": "未定義語を調べるときは下書きキャプチャを使い、候補行を押して登録フォームへ入れてから「登録依頼をコピー」を使ってください。既存ルールの差し替えは候補セルの「コピー」で行えます。",
    "capture_title": "下書きキャプチャ",
    "capture_description": "原文を貼り付けると、専門用語より会話内の未定義語を優先するローカル草案プレビューを生成します。完全な AI 判定ではありません。",
    "capture_placeholder": "解析したい原文を貼り付け...",
    "capture_btn": "下書きを解析",
    "capture_copy_output_btn": "下書き出力をコピー",
    "capture_copy_output_copied": "下書き出力をコピーしました。",
    "capture_copy_prompt_btn": "AI 用プロンプトをコピー",
    "capture_copy_prompt_copied": "AI 用プロンプトをコピーしました。",
    "capture_result_title": "下書き出力",
    "capture_empty": "原文を貼り付けて解析してください。",
    "capture_none": "プレビュー候補はありません。",
    "capture_note": "これは未定義語向けのローカルプレビューです。より厳密な判断が必要な場合は「AI 用プロンプトをコピー」を使ってチャット側で確認してください。",
    "capture_ready": "草案プレビューを生成しました。行を押すと登録フォームへ反映されます。",
    "capture_loaded": "「{term}」を登録フォームへ反映しました。まだ登録は完了していません。",
    "capture_current_label": "（現在）",
    "capture_candidate1_label": "（候補 1）",
    "capture_candidate2_label": "（候補 2）",
    "capture_footer": "候補 1 は現在のローカル草案プレビューです。チャット側で見直したい場合は「AI 用プロンプトをコピー」を使ってください。",
    "capture_keep_current": "現状維持",
    "capture_prompt_header": "次の原文だけを対象に veil-capture の意味論で判定し、veil-capture 形式で返してください。",
    "register_title": "新しいルールを登録",
    "field_term": "用語",
    "field_preferred": "推奨表現",
    "field_alt2": "候補 2",
    "field_alt3": "候補 3",
    "register_term_placeholder": "例: current state",
    "register_preferred_placeholder": "例: present state",
    "register_alt2_placeholder": "任意の代替候補",
    "register_alt3_placeholder": "任意の代替候補",
    "register_btn": "登録依頼をコピー",
    "register_commands_btn": "コマンドをコピー",
    "register_missing": "用語と推奨表現は必須です。",
    "register_copied": "登録依頼をコピーしました。",
    "register_commands_copied": "登録コマンドをコピーしました。",
    "col_term": "用語",
    "col_preferred": "推奨表現（候補 1）",
    "col_alt2": "候補 2",
    "col_alt3": "候補 3",
    "col_actions": "操作",
    "copy_btn": "コピー",
    "delete_btn": "削除",
    "copy_done": "コピーしました",
    "copy_manual": "クリップボードが使えません。次の内容を手動でコピーしてください:",
    "copy_manual_done": "手動コピー用プロンプトを開きました。",
    "copy_failed": "コピーに失敗しました。プロンプトの内容を手動でコピーしてください。",
    "count_registered": "{n} 件登録済み",
    "count_matching": "{n} 件一致",
    "copy_instruction": "'{term}' を '{candidate}' に変更",
    "delete_instruction_header": "このルールを削除するには次のコマンドを実行してください:",
    "delete_copied": "削除コマンドをコピーしました。",
    "register_instruction_header": "このルールを登録するには次のコマンドを実行してください:",
    "register_prompt_header": "この VEIL ルールを現在のリポジトリに登録してください:",
    "register_prompt_footer": "SQLite canonical を更新し、mirror と veil.html を再生成してください。",
}

_HTML_UI_KO: dict[str, str] = {
    **_HTML_UI_EN,
    "lang": "ko",
    "title": "VEIL - 용어 규칙",
    "search_placeholder": "용어 검색...",
    "instruction": "등록된 용어의 기본 표현을 바꾸려면 후보 셀의 Copy를 누르세요. 클립보드를 쓸 수 없으면 수동 복사 프롬프트를 엽니다.",
    "capture_title": "초안 캡처",
    "capture_description": "원문을 붙여 넣으면 전문 용어보다 대화 안의 미정의 표현을 우선하는 로컬 미리보기를 만듭니다.",
    "capture_placeholder": "분석할 텍스트를 붙여 넣으세요...",
    "capture_btn": "초안 분석",
    "capture_copy_output_btn": "초안 출력 복사",
    "capture_copy_output_copied": "초안 출력을 복사했습니다.",
    "capture_copy_prompt_btn": "AI 프롬프트 복사",
    "capture_copy_prompt_copied": "AI 프롬프트를 복사했습니다.",
    "capture_result_title": "초안 출력",
    "capture_empty": "텍스트를 붙여 넣고 분석하세요.",
    "capture_none": "미리보기 후보가 없습니다.",
    "capture_note": "이것은 미정의 표현을 위한 로컬 미리보기입니다. 더 정확한 판단이 필요하면 AI 프롬프트 복사를 사용하세요.",
    "capture_ready": "초안 미리보기를 생성했습니다. 줄을 누르면 등록 양식에 반영됩니다.",
    "capture_loaded": "'{term}' 항목을 등록 양식에 반영했습니다. 아직 등록은 완료되지 않았습니다.",
    "capture_current_label": " (현재)",
    "capture_candidate1_label": " (후보 1)",
    "capture_candidate2_label": " (후보 2)",
    "capture_footer": "후보 1은 현재 로컬 초안입니다. 채팅에서 다시 검토하려면 AI 프롬프트 복사를 사용하세요.",
    "capture_keep_current": "현재 유지",
    "capture_prompt_header": "다음 텍스트만 대상으로 veil-capture 의미론으로 판단하고, veil-capture 형식으로 반환하세요.",
    "register_title": "새 규칙 등록",
    "field_term": "용어",
    "field_preferred": "기본 표현",
    "field_alt2": "후보 2",
    "field_alt3": "후보 3",
    "register_term_placeholder": "예: current state",
    "register_preferred_placeholder": "예: present state",
    "register_alt2_placeholder": "선택 대안",
    "register_alt3_placeholder": "선택 대안",
    "register_btn": "등록 요청 복사",
    "register_commands_btn": "명령 복사",
    "register_missing": "용어와 기본 표현은 필수입니다.",
    "register_copied": "등록 요청을 복사했습니다.",
    "register_commands_copied": "등록 명령을 복사했습니다.",
    "col_term": "용어",
    "col_preferred": "기본 표현 (후보 1)",
    "col_alt2": "후보 2",
    "col_alt3": "후보 3",
    "col_actions": "동작",
    "copy_btn": "복사",
    "delete_btn": "삭제",
    "copy_done": "복사됨",
    "copy_manual": "클립보드를 사용할 수 없습니다. 다음 텍스트를 직접 복사하세요:",
    "copy_manual_done": "수동 복사 프롬프트를 열었습니다.",
    "copy_failed": "복사에 실패했습니다. 프롬프트의 텍스트를 직접 복사하세요.",
    "count_registered": "{n}개 등록됨",
    "count_matching": "{n}개 일치",
    "copy_instruction": "'{term}'를 '{candidate}'로 변경",
    "delete_instruction_header": "이 규칙을 삭제하려면 다음 명령을 실행하세요:",
    "delete_copied": "삭제 명령을 복사했습니다.",
    "register_instruction_header": "이 규칙을 등록하려면 다음 명령을 실행하세요:",
    "register_prompt_header": "현재 리포지토리에 이 VEIL 규칙을 등록하세요:",
    "register_prompt_footer": "SQLite canonical을 업데이트한 뒤 mirror와 veil.html을 다시 생성하세요.",
}

_HTML_UI_ZH_HANS: dict[str, str] = {
    **_HTML_UI_EN,
    "lang": "zh-CN",
    "title": "VEIL - 词汇规则",
    "search_placeholder": "搜索术语...",
    "instruction": "如果要修改已登记术语的首选表达，请点击候选单元格中的 Copy。若无法访问剪贴板，VEIL 会打开手动复制提示框。",
    "capture_title": "草稿捕获",
    "capture_description": "在这里粘贴原文，可生成优先关注对话内未定义表达、而非专业术语的本地预览。",
    "capture_placeholder": "粘贴要分析的文本...",
    "capture_btn": "分析草稿",
    "capture_copy_output_btn": "复制草稿输出",
    "capture_copy_output_copied": "已复制草稿输出。",
    "capture_copy_prompt_btn": "复制 AI 提示词",
    "capture_copy_prompt_copied": "已复制 AI 提示词。",
    "capture_result_title": "草稿输出",
    "capture_empty": "请粘贴文本后再分析。",
    "capture_none": "没有预览候选。",
    "capture_note": "这是面向未定义表达的本地预览。如果需要更严格的判断，请使用“复制 AI 提示词”。",
    "capture_ready": "已生成草稿预览。点击某一行可将其载入登记表单。",
    "capture_loaded": "已将“{term}”载入登记表单。此时尚未完成登记。",
    "capture_current_label": "（当前）",
    "capture_candidate1_label": "（候选 1）",
    "capture_candidate2_label": "（候选 2）",
    "capture_footer": "候选 1 是当前本地草稿。若要在聊天侧复核，请使用“复制 AI 提示词”。",
    "capture_keep_current": "保持当前",
    "capture_prompt_header": "仅针对以下文本使用 veil-capture 语义进行判断，并以 veil-capture 格式返回。",
    "register_title": "登记新规则",
    "field_term": "术语",
    "field_preferred": "首选表达",
    "field_alt2": "候选 2",
    "field_alt3": "候选 3",
    "register_term_placeholder": "例如: current state",
    "register_preferred_placeholder": "例如: present state",
    "register_alt2_placeholder": "可选替代项",
    "register_alt3_placeholder": "可选替代项",
    "register_btn": "复制登记请求",
    "register_commands_btn": "复制命令",
    "register_missing": "术语和首选表达为必填项。",
    "register_copied": "已复制登记请求。",
    "register_commands_copied": "已复制登记命令。",
    "col_term": "术语",
    "col_preferred": "首选表达（候选 1）",
    "col_alt2": "候选 2",
    "col_alt3": "候选 3",
    "col_actions": "操作",
    "copy_btn": "复制",
    "delete_btn": "删除",
    "copy_done": "已复制",
    "copy_manual": "无法访问剪贴板。请手动复制以下文本：",
    "copy_manual_done": "已打开手动复制提示框。",
    "copy_failed": "复制失败。请从提示框中手动复制文本。",
    "count_registered": "已登记 {n} 个术语",
    "count_matching": "匹配 {n} 个术语",
    "copy_instruction": "将“{term}”改为“{candidate}”",
    "delete_instruction_header": "要删除此规则，请运行以下命令：",
    "delete_copied": "已复制删除命令。",
    "register_instruction_header": "要登记此规则，请运行以下命令：",
    "register_prompt_header": "请在当前仓库中登记这条 VEIL 规则：",
    "register_prompt_footer": "更新 SQLite canonical，然后重新生成 mirror 和 veil.html。",
}

_HTML_UI_ZH_HANT: dict[str, str] = {
    **_HTML_UI_EN,
    "lang": "zh-TW",
    "title": "VEIL - 詞彙規則",
    "search_placeholder": "搜尋術語...",
    "instruction": "如果要修改已登錄術語的首選表達，請點選候選儲存格中的 Copy。若無法使用剪貼簿，VEIL 會開啟手動複製提示。",
    "capture_title": "草稿擷取",
    "capture_description": "在這裡貼上原文，可產生優先關注對話內未定義表達、而非專業術語的本機預覽。",
    "capture_placeholder": "貼上要分析的文字...",
    "capture_btn": "分析草稿",
    "capture_copy_output_btn": "複製草稿輸出",
    "capture_copy_output_copied": "已複製草稿輸出。",
    "capture_copy_prompt_btn": "複製 AI 提示詞",
    "capture_copy_prompt_copied": "已複製 AI 提示詞。",
    "capture_result_title": "草稿輸出",
    "capture_empty": "請先貼上文字再分析。",
    "capture_none": "沒有預覽候選。",
    "capture_note": "這是面向未定義表達的本機預覽。如果需要更嚴格的判定，請使用「複製 AI 提示詞」。",
    "capture_ready": "已產生草稿預覽。點選某一行可將其載入登錄表單。",
    "capture_loaded": "已將「{term}」載入登錄表單。此時尚未完成登錄。",
    "capture_current_label": "（目前）",
    "capture_candidate1_label": "（候選 1）",
    "capture_candidate2_label": "（候選 2）",
    "capture_footer": "候選 1 是目前的本機草稿。若要在聊天端重新檢查，請使用「複製 AI 提示詞」。",
    "capture_keep_current": "保留目前",
    "capture_prompt_header": "請只針對以下文字以 veil-capture 語義進行判定，並以 veil-capture 格式回傳。",
    "register_title": "登錄新規則",
    "field_term": "術語",
    "field_preferred": "首選表達",
    "field_alt2": "候選 2",
    "field_alt3": "候選 3",
    "register_term_placeholder": "例如: current state",
    "register_preferred_placeholder": "例如: present state",
    "register_alt2_placeholder": "可選替代項",
    "register_alt3_placeholder": "可選替代項",
    "register_btn": "複製登錄請求",
    "register_commands_btn": "複製命令",
    "register_missing": "術語和首選表達為必填。",
    "register_copied": "已複製登錄請求。",
    "register_commands_copied": "已複製登錄命令。",
    "col_term": "術語",
    "col_preferred": "首選表達（候選 1）",
    "col_alt2": "候選 2",
    "col_alt3": "候選 3",
    "col_actions": "操作",
    "copy_btn": "複製",
    "delete_btn": "刪除",
    "copy_done": "已複製",
    "copy_manual": "無法使用剪貼簿。請手動複製以下文字：",
    "copy_manual_done": "已開啟手動複製提示。",
    "copy_failed": "複製失敗。請從提示中手動複製文字。",
    "count_registered": "已登錄 {n} 個術語",
    "count_matching": "符合 {n} 個術語",
    "copy_instruction": "將「{term}」改成「{candidate}」",
    "delete_instruction_header": "若要刪除此規則，請執行以下命令：",
    "delete_copied": "已複製刪除命令。",
    "register_instruction_header": "若要登錄此規則，請執行以下命令：",
    "register_prompt_header": "請在目前的儲存庫中登錄這條 VEIL 規則：",
    "register_prompt_footer": "更新 SQLite canonical，然後重新產生 mirror 和 veil.html。",
}

_HTML_UI_AR: dict[str, str] = {
    **_HTML_UI_EN,
    "lang": "ar",
    "title": "VEIL - قواعد المصطلحات",
    "search_placeholder": "ابحث في المصطلحات...",
    "instruction": "لتغيير الصيغة المفضلة لمصطلح مسجل، اضغط Copy في خلية المرشح. إذا تعذر استخدام الحافظة، سيفتح VEIL نافذة نسخ يدوي.",
    "capture_title": "التقاط المسودة",
    "capture_description": "الصق النص هنا للحصول على معاينة محلية تركّز على العبارات غير المعرّفة داخل المحادثة أكثر من المصطلحات المتخصصة.",
    "capture_placeholder": "الصق النص المراد تحليله...",
    "capture_btn": "تحليل المسودة",
    "capture_copy_output_btn": "نسخ مخرجات المسودة",
    "capture_copy_output_copied": "تم نسخ مخرجات المسودة.",
    "capture_copy_prompt_btn": "نسخ موجّه الذكاء الاصطناعي",
    "capture_copy_prompt_copied": "تم نسخ موجّه الذكاء الاصطناعي.",
    "capture_result_title": "مخرجات المسودة",
    "capture_empty": "الصق النص ثم شغّل التحليل.",
    "capture_none": "لا توجد عناصر للمعاينة.",
    "capture_note": "هذه معاينة محلية للعبارات غير المعرّفة. إذا كنت تحتاج حكماً أدق، فاستخدم \"نسخ موجّه الذكاء الاصطناعي\".",
    "capture_ready": "تم إنشاء معاينة المسودة. اضغط على سطر لتحميله إلى نموذج التسجيل.",
    "capture_loaded": "تم تحميل \"{term}\" إلى نموذج التسجيل. لم يكتمل التسجيل بعد.",
    "capture_current_label": " (الحالي)",
    "capture_candidate1_label": " (المرشح 1)",
    "capture_candidate2_label": " (المرشح 2)",
    "capture_footer": "المرشح 1 هو المسودة المحلية الحالية. إذا أردت مراجعته في الدردشة، فاستخدم \"نسخ موجّه الذكاء الاصطناعي\".",
    "capture_keep_current": "الإبقاء على الحالي",
    "capture_prompt_header": "استخدم دلالات veil-capture على النص التالي فقط، وأعد النتيجة بصيغة veil-capture.",
    "register_title": "تسجيل قاعدة جديدة",
    "field_term": "المصطلح",
    "field_preferred": "الصيغة المفضلة",
    "field_alt2": "المرشح 2",
    "field_alt3": "المرشح 3",
    "register_term_placeholder": "مثال: current state",
    "register_preferred_placeholder": "مثال: present state",
    "register_alt2_placeholder": "بديل اختياري",
    "register_alt3_placeholder": "بديل اختياري",
    "register_btn": "نسخ طلب التسجيل",
    "register_commands_btn": "نسخ الأوامر",
    "register_missing": "المصطلح والصيغة المفضلة مطلوبان.",
    "register_copied": "تم نسخ طلب التسجيل.",
    "register_commands_copied": "تم نسخ أوامر التسجيل.",
    "col_term": "المصطلح",
    "col_preferred": "الصيغة المفضلة (المرشح 1)",
    "col_alt2": "المرشح 2",
    "col_alt3": "المرشح 3",
    "col_actions": "الإجراءات",
    "copy_btn": "نسخ",
    "delete_btn": "حذف",
    "copy_done": "تم النسخ",
    "copy_manual": "تعذر الوصول إلى الحافظة. انسخ هذا النص يدوياً:",
    "copy_manual_done": "تم فتح نافذة النسخ اليدوي.",
    "copy_failed": "فشل النسخ. انسخ النص يدوياً من النافذة.",
    "count_registered": "تم تسجيل {n} مصطلحاً",
    "count_matching": "{n} مصطلحات مطابقة",
    "copy_instruction": "غيّر '{term}' إلى '{candidate}'",
    "delete_instruction_header": "نفّذ الأوامر التالية لحذف هذه القاعدة:",
    "delete_copied": "تم نسخ أوامر الحذف.",
    "register_instruction_header": "نفّذ الأوامر التالية لتسجيل هذه القاعدة:",
    "register_prompt_header": "سجّل قاعدة VEIL هذه في المستودع الحالي:",
    "register_prompt_footer": "حدّث SQLite canonical ثم أعد توليد mirror و veil.html.",
}

_HTML_UI_BY_LANG: dict[str, dict[str, str]] = {
    "en": _HTML_UI_EN,
    "ja": _HTML_UI_JA,
    "ko": _HTML_UI_KO,
    "zh-hans": _HTML_UI_ZH_HANS,
    "zh-hant": _HTML_UI_ZH_HANT,
    "ar": _HTML_UI_AR,
}


def get_html_ui_for_lang(lang: str | None) -> dict[str, str]:
    normalized = (lang or "en").strip().lower().replace("_", "-")
    if normalized.startswith("zh-cn") or normalized.startswith("zh-sg") or normalized == "zh":
        key = "zh-hans"
    elif normalized.startswith("zh-tw") or normalized.startswith("zh-hk") or normalized.startswith("zh-mo"):
        key = "zh-hant"
    elif normalized.startswith("ja"):
        key = "ja"
    elif normalized.startswith("ko"):
        key = "ko"
    elif normalized.startswith("ar"):
        key = "ar"
    else:
        key = "en"
    return dict(_HTML_UI_BY_LANG.get(key, _HTML_UI_EN))
