from __future__ import annotations

from pathlib import Path


_HTML_TEMPLATE = Path(__file__).with_name("veil_review_template.html").read_text(encoding="utf-8")


_HTML_UI_EN: dict[str, str] = {
    "lang": "en",
    "title": "VEIL - Vocabulary Rules",
    "search_placeholder": "Search terms...",
    "instruction": "Normal task-close review runs in the installed Skill. This page is a recovery surface: copy the complete text for semantic AI review, or optionally run the local diagnostic preview. Registered rules below can be reviewed or changed.",
    "capture_title": "AI review recovery",
    "capture_description": "Paste text and copy one complete AI review request. The optional local preview is regex-based and may miss or misclassify decisions.",
    "capture_placeholder": "Paste the exact text to review...",
    "capture_btn": "Run local diagnostic preview",
    "capture_exceptions_copy_btn": "Copy complete AI review request",
    "capture_exceptions_copied": "Complete AI review request copied.",
    "capture_exceptions_prompt_header": "Run the installed VEIL capture workflow on this exact text.",
    "capture_exceptions_prompt_footer": "Use semantic frames contract v2 and a separate critic pass. Do not treat the HTML preview as semantic evidence or write before acceptance.",
    "capture_exceptions_propose_marker": "[propose preferred form]",
    "capture_copy_output_btn": "Copy Draft Output",
    "capture_copy_output_copied": "Draft output copied.",
    "capture_copy_prompt_btn": "Copy AI Prompt",
    "capture_copy_prompt_copied": "AI prompt copied.",
    "capture_result_title": "Local diagnostic preview",
    "capture_empty": "Paste text to copy an AI review request or run the optional preview.",
    "capture_none": "The local preview found no possible exception. This does not complete semantic AI review.",
    "capture_note": "Recovery only: the local preview is not proof that the conversation was understood. Send the complete text to AI before any write.",
    "capture_ready": "The local preview found possible review items. Send the complete text to AI before any write.",
    "capture_loaded": "'{term}' came from the diagnostic preview. Verify it with AI before saving.",
    "capture_current_label": " (current)",
    "capture_candidate1_label": " (preferred)",
    "capture_candidate2_label": " (alternative)",
    "capture_footer": "The local preview is diagnostic only; semantic AI review remains authoritative for the normal flow.",
    "capture_keep_current": "keep current wording",
    "capture_prompt_header": "Run the installed VEIL capture workflow on the exact text below. Use evidence-backed semantic decision frames (contract v2) and a separate critic pass. Do not use the HTML regex preview as semantic proof. Keep automatic outcomes silent and ask at most one combined question for unresolved durable decisions.",
    "capture_prompt_footer": "Use exact source evidence. Preserve supplied preferred forms, and do not write any rule until the user has accepted the combined decision.",
    "register_title": "Register or change a rule",
    "advanced_options": "Optional alternatives and recovery commands",
    "field_term": "Term",
    "field_preferred": "Preferred",
    "field_alt2": "Alternative 1",
    "field_alt3": "Alternative 2",
    "register_term_placeholder": "e.g. current state",
    "register_preferred_placeholder": "e.g. present state",
    "register_alt2_placeholder": "Optional alternative",
    "register_alt3_placeholder": "Optional alternative",
    "register_btn": "Copy save request",
    "register_commands_btn": "Advanced: copy commands",
    "register_missing": "Term and preferred form are required.",
    "register_copied": "Registration request copied.",
    "register_commands_copied": "Registration commands copied.",
    "col_term": "Term",
    "col_preferred": "Preferred",
    "col_alt2": "Alternative 1",
    "col_alt3": "Alternative 2",
    "col_actions": "Actions",
    "copy_btn": "Copy",
    "delete_btn": "Delete",
    "copy_done": "Copied",
    "copy_manual": "Clipboard access is unavailable. Copy this text manually:",
    "copy_manual_done": "Manual copy prompt opened.",
    "copy_failed": "Copy failed. Copy the text manually from the prompt.",
    "count_registered": "{n} terms registered",
    "count_matching": "{n} terms matching",
    "copy_instruction": "Change '{term}' to '{candidate}'",
    "delete_instruction_header": "Run these commands to delete this rule:",
    "delete_copied": "Deletion commands copied.",
    "register_instruction_header": "Run these commands to register this rule:",
    "register_prompt_header": "Register this VEIL rule in the current repository:",
    "register_prompt_footer": "Update the SQLite canonical, then regenerate the mirror and veil.html.",
}

_HTML_UI_JA: dict[str, str] = {
    "lang": "ja",
    "title": "VEIL - 語彙ルール",
    "search_placeholder": "用語を検索...",
    "instruction": "通常のタスク終了時はインストール済みSkillが確認します。この画面は復旧用です。全文をAI確認依頼としてコピーするか、必要な場合だけローカル診断を実行してください。登録済みルールは下の一覧で見直せます。",
    "capture_title": "AI確認の復旧",
    "capture_description": "原文を貼り付け、完全なAI確認依頼を1回コピーします。任意のローカル診断は正規表現ベースで、判断の見落としや誤分類があり得ます。",
    "capture_placeholder": "確認する原文をそのまま貼り付け...",
    "capture_btn": "ローカル診断を実行",
    "capture_exceptions_copy_btn": "完全なAI確認依頼をコピー",
    "capture_exceptions_copied": "完全なAI確認依頼をコピーしました。",
    "capture_exceptions_prompt_header": "次の原文にインストール済みVEIL captureを実行してください。",
    "capture_exceptions_prompt_footer": "意味フレームcontract v2と独立criticを使い、HTML診断を意味理解の証拠にせず、承認前は書き込まないでください。",
    "capture_exceptions_propose_marker": "［推奨表現を提案］",
    "capture_copy_output_btn": "下書き出力をコピー",
    "capture_copy_output_copied": "下書き出力をコピーしました。",
    "capture_copy_prompt_btn": "AI 用プロンプトをコピー",
    "capture_copy_prompt_copied": "AI 用プロンプトをコピーしました。",
    "capture_result_title": "ローカル診断プレビュー",
    "capture_empty": "原文を貼り付けてAI確認依頼をコピーするか、任意の診断を実行してください。",
    "capture_none": "ローカル診断では例外候補が見つかりませんでした。意味を扱うAI確認は完了していません。",
    "capture_note": "復旧専用です。ローカル診断は会話を理解できた証拠ではありません。書込み前に全文をAIへ渡してください。",
    "capture_ready": "ローカル診断で確認候補が見つかりました。書込み前に全文をAIへ渡してください。",
    "capture_loaded": "「{term}」は診断プレビュー由来です。保存前にAIで確認してください。",
    "capture_current_label": "（現在）",
    "capture_candidate1_label": "（推奨）",
    "capture_candidate2_label": "（代替）",
    "capture_footer": "ローカルプレビューは診断専用です。通常フローの判断は意味を扱うAI確認が担当します。",
    "capture_keep_current": "現在の表記を維持",
    "capture_prompt_header": "次の原文にインストール済みVEIL captureを実行してください。根拠付き意味決定フレーム（contract v2）と独立criticを使い、HTMLの正規表現プレビューを意味理解の証拠にしないでください。自動処理結果は表示せず、未解決の永続判断がある場合だけ全件を1回の質問にまとめてください。",
    "capture_prompt_footer": "原文の正確な根拠を使い、指定済みの推奨表現を維持し、まとめた判断が承認されるまでルールを書き込まないでください。",
    "register_title": "ルールを登録・変更",
    "advanced_options": "任意の代替表現・復旧用コマンド",
    "field_term": "用語",
    "field_preferred": "推奨表現",
    "field_alt2": "代替表現 1",
    "field_alt3": "代替表現 2",
    "register_term_placeholder": "例: current state",
    "register_preferred_placeholder": "例: present state",
    "register_alt2_placeholder": "任意の代替候補",
    "register_alt3_placeholder": "任意の代替候補",
    "register_btn": "保存依頼をコピー",
    "register_commands_btn": "詳細：コマンドをコピー",
    "register_missing": "用語と推奨表現は必須です。",
    "register_copied": "登録依頼をコピーしました。",
    "register_commands_copied": "登録コマンドをコピーしました。",
    "col_term": "用語",
    "col_preferred": "推奨表現",
    "col_alt2": "代替表現 1",
    "col_alt3": "代替表現 2",
    "col_actions": "操作",
    "copy_btn": "コピー",
    "delete_btn": "削除",
    "copy_done": "コピーしました",
    "copy_manual": "クリップボードが使えません。次の内容を手動でコピーしてください:",
    "copy_manual_done": "手動コピー用プロンプトを開きました。",
    "copy_failed": "コピーに失敗しました。プロンプトの内容を手動でコピーしてください。",
    "count_registered": "{n} 件登録済み",
    "count_matching": "{n} 件一致",
    "copy_instruction": "'{term}' を '{candidate}' に変更",
    "delete_instruction_header": "このルールを削除するには次のコマンドを実行してください:",
    "delete_copied": "削除コマンドをコピーしました。",
    "register_instruction_header": "このルールを登録するには次のコマンドを実行してください:",
    "register_prompt_header": "この VEIL ルールを現在のリポジトリに登録してください:",
    "register_prompt_footer": "SQLite canonical を更新し、mirror と veil.html を再生成してください。",
}

_HTML_UI_KO: dict[str, str] = {
    **_HTML_UI_EN,
    "lang": "ko",
    "title": "VEIL - 용어 규칙",
    "search_placeholder": "용어 검색...",
    "instruction": "일반 작업 종료 검토는 설치된 Skill에서 실행됩니다. 이 페이지는 복구용입니다. 전체 텍스트를 의미 기반 AI 검토 요청으로 복사하거나 필요할 때만 로컬 진단을 실행하세요. 아래에서 등록된 규칙을 검토하거나 변경할 수 있습니다.",
    "capture_title": "AI 검토 복구",
    "capture_description": "원문을 붙여 넣고 완전한 AI 검토 요청 하나를 복사하세요. 선택적 로컬 미리보기는 정규식 기반이라 결정을 놓치거나 잘못 분류할 수 있습니다.",
    "capture_placeholder": "검토할 정확한 원문을 붙여 넣으세요...",
    "capture_btn": "로컬 진단 미리보기 실행",
    "capture_exceptions_copy_btn": "완전한 AI 검토 요청 복사",
    "capture_exceptions_copied": "완전한 AI 검토 요청을 복사했습니다.",
    "capture_exceptions_prompt_header": "이 정확한 원문에 설치된 VEIL capture를 실행하세요.",
    "capture_exceptions_prompt_footer": "의미 프레임 contract v2와 별도 critic을 사용하고 HTML 미리보기를 의미 증거로 취급하거나 승인 전에 기록하지 마세요.",
    "capture_exceptions_propose_marker": "[기본 표현 제안]",
    "capture_copy_output_btn": "초안 출력 복사",
    "capture_copy_output_copied": "초안 출력을 복사했습니다.",
    "capture_copy_prompt_btn": "AI 프롬프트 복사",
    "capture_copy_prompt_copied": "AI 프롬프트를 복사했습니다.",
    "capture_result_title": "로컬 진단 미리보기",
    "capture_empty": "원문을 붙여 AI 검토 요청을 복사하거나 선택적 미리보기를 실행하세요.",
    "capture_none": "로컬 미리보기에서 가능한 예외를 찾지 못했습니다. 의미 기반 AI 검토는 완료되지 않았습니다.",
    "capture_note": "복구 전용입니다. 로컬 미리보기는 대화를 이해했다는 증거가 아닙니다. 기록 전에 전체 텍스트를 AI에 보내세요.",
    "capture_ready": "로컬 미리보기에서 검토 가능 항목을 찾았습니다. 기록 전에 전체 텍스트를 AI에 보내세요.",
    "capture_loaded": "'{term}'은 진단 미리보기에서 가져왔습니다. 저장 전에 AI로 확인하세요.",
    "capture_current_label": " (현재)",
    "capture_candidate1_label": " (기본)",
    "capture_candidate2_label": " (대안)",
    "capture_footer": "로컬 미리보기는 진단 전용이며 일반 흐름의 판단은 의미 기반 AI 검토가 담당합니다.",
    "capture_keep_current": "현재 표현 유지",
    "capture_prompt_header": "아래 정확한 원문에 설치된 VEIL capture를 실행하세요. 근거가 있는 의미 결정 프레임(contract v2)과 별도 critic을 사용하고 HTML 정규식 미리보기를 의미 증거로 사용하지 마세요. 자동 결과는 표시하지 말고 해결되지 않은 지속적 결정만 하나의 질문으로 묶으세요.",
    "capture_prompt_footer": "정확한 원문 근거를 사용하고 제공된 기본 표현을 유지하며 사용자가 통합 결정을 승인할 때까지 규칙을 기록하지 마세요.",
    "register_title": "규칙 등록 또는 변경",
    "advanced_options": "선택 대안 및 복구 명령",
    "field_term": "용어",
    "field_preferred": "기본 표현",
    "field_alt2": "대안 1",
    "field_alt3": "대안 2",
    "register_term_placeholder": "예: current state",
    "register_preferred_placeholder": "예: present state",
    "register_alt2_placeholder": "선택 대안",
    "register_alt3_placeholder": "선택 대안",
    "register_btn": "저장 요청 복사",
    "register_commands_btn": "고급: 명령 복사",
    "register_missing": "용어와 기본 표현은 필수입니다.",
    "register_copied": "등록 요청을 복사했습니다.",
    "register_commands_copied": "등록 명령을 복사했습니다.",
    "col_term": "용어",
    "col_preferred": "기본 표현",
    "col_alt2": "대안 1",
    "col_alt3": "대안 2",
    "col_actions": "동작",
    "copy_btn": "복사",
    "delete_btn": "삭제",
    "copy_done": "복사됨",
    "copy_manual": "클립보드를 사용할 수 없습니다. 다음 텍스트를 직접 복사하세요:",
    "copy_manual_done": "수동 복사 프롬프트를 열었습니다.",
    "copy_failed": "복사에 실패했습니다. 프롬프트의 텍스트를 직접 복사하세요.",
    "count_registered": "{n}개 등록됨",
    "count_matching": "{n}개 일치",
    "copy_instruction": "'{term}'를 '{candidate}'로 변경",
    "delete_instruction_header": "이 규칙을 삭제하려면 다음 명령을 실행하세요:",
    "delete_copied": "삭제 명령을 복사했습니다.",
    "register_instruction_header": "이 규칙을 등록하려면 다음 명령을 실행하세요:",
    "register_prompt_header": "현재 리포지토리에 이 VEIL 규칙을 등록하세요:",
    "register_prompt_footer": "SQLite canonical을 업데이트한 뒤 mirror와 veil.html을 다시 생성하세요.",
}

_HTML_UI_ZH_HANS: dict[str, str] = {
    **_HTML_UI_EN,
    "lang": "zh-CN",
    "title": "VEIL - 词汇规则",
    "search_placeholder": "搜索术语...",
    "instruction": "常规任务结束审查由已安装的 Skill 执行。本页面仅用于恢复：复制完整原文进行语义 AI 审查，或按需运行本地诊断。下方可查看或修改已登记规则。",
    "capture_title": "AI 审查恢复",
    "capture_description": "粘贴原文并复制一份完整 AI 审查请求。可选的本地预览基于正则表达式，可能遗漏或误分类决定。",
    "capture_placeholder": "粘贴需要审查的准确原文...",
    "capture_btn": "运行本地诊断预览",
    "capture_exceptions_copy_btn": "复制完整 AI 审查请求",
    "capture_exceptions_copied": "已复制完整 AI 审查请求。",
    "capture_exceptions_prompt_header": "请对这段准确原文运行已安装的 VEIL capture。",
    "capture_exceptions_prompt_footer": "使用语义框架 contract v2 和独立 critic；不要把 HTML 预览当作语义证据，也不要在接受前写入。",
    "capture_exceptions_propose_marker": "[提出首选表达]",
    "capture_copy_output_btn": "复制草稿输出",
    "capture_copy_output_copied": "已复制草稿输出。",
    "capture_copy_prompt_btn": "复制 AI 提示词",
    "capture_copy_prompt_copied": "已复制 AI 提示词。",
    "capture_result_title": "本地诊断预览",
    "capture_empty": "粘贴原文以复制 AI 审查请求，或运行可选预览。",
    "capture_none": "本地预览未发现可能的例外。这不代表语义 AI 审查已完成。",
    "capture_note": "仅用于恢复。本地预览不能证明已理解对话；任何写入前都应把完整原文交给 AI。",
    "capture_ready": "本地预览发现了可能需要审查的项目。任何写入前都应把完整原文交给 AI。",
    "capture_loaded": "“{term}”来自诊断预览。保存前请由 AI 验证。",
    "capture_current_label": "（当前）",
    "capture_candidate1_label": "（首选）",
    "capture_candidate2_label": "（替代表达）",
    "capture_footer": "本地预览仅用于诊断；常规流程的决定由语义 AI 审查负责。",
    "capture_keep_current": "保持当前表述",
    "capture_prompt_header": "请对下方准确原文运行已安装的 VEIL capture。使用带证据的语义决定框架（contract v2）和独立 critic，不要把 HTML 正则预览当作语义证据。自动结果保持静默，仅将未解决的持久决定合并为一个问题。",
    "capture_prompt_footer": "使用准确的原文证据，保留已提供的首选表达，并在用户接受合并决定前不要写入任何规则。",
    "register_title": "登记或修改规则",
    "advanced_options": "可选替代表达与恢复命令",
    "field_term": "术语",
    "field_preferred": "首选表达",
    "field_alt2": "替代表达 1",
    "field_alt3": "替代表达 2",
    "register_term_placeholder": "例如: current state",
    "register_preferred_placeholder": "例如: present state",
    "register_alt2_placeholder": "可选替代项",
    "register_alt3_placeholder": "可选替代项",
    "register_btn": "复制保存请求",
    "register_commands_btn": "高级：复制命令",
    "register_missing": "术语和首选表达为必填项。",
    "register_copied": "已复制登记请求。",
    "register_commands_copied": "已复制登记命令。",
    "col_term": "术语",
    "col_preferred": "首选表达",
    "col_alt2": "替代表达 1",
    "col_alt3": "替代表达 2",
    "col_actions": "操作",
    "copy_btn": "复制",
    "delete_btn": "删除",
    "copy_done": "已复制",
    "copy_manual": "无法访问剪贴板。请手动复制以下文本：",
    "copy_manual_done": "已打开手动复制提示框。",
    "copy_failed": "复制失败。请从提示框中手动复制文本。",
    "count_registered": "已登记 {n} 个术语",
    "count_matching": "匹配 {n} 个术语",
    "copy_instruction": "将“{term}”改为“{candidate}”",
    "delete_instruction_header": "要删除此规则，请运行以下命令：",
    "delete_copied": "已复制删除命令。",
    "register_instruction_header": "要登记此规则，请运行以下命令：",
    "register_prompt_header": "请在当前仓库中登记这条 VEIL 规则：",
    "register_prompt_footer": "更新 SQLite canonical，然后重新生成 mirror 和 veil.html。",
}

_HTML_UI_ZH_HANT: dict[str, str] = {
    **_HTML_UI_EN,
    "lang": "zh-TW",
    "title": "VEIL - 詞彙規則",
    "search_placeholder": "搜尋術語...",
    "instruction": "一般任務結束檢視由已安裝的 Skill 執行。本頁僅供復原：複製完整原文進行語意 AI 檢視，或視需要執行本機診斷。下方可檢視或修改已登錄規則。",
    "capture_title": "AI 檢視復原",
    "capture_description": "貼上原文並複製一份完整 AI 檢視請求。選用的本機預覽以正規表示式為基礎，可能遺漏或誤分類決定。",
    "capture_placeholder": "貼上需要檢視的準確原文...",
    "capture_btn": "執行本機診斷預覽",
    "capture_exceptions_copy_btn": "複製完整 AI 檢視請求",
    "capture_exceptions_copied": "已複製完整 AI 檢視請求。",
    "capture_exceptions_prompt_header": "請對這段準確原文執行已安裝的 VEIL capture。",
    "capture_exceptions_prompt_footer": "使用語意框架 contract v2 與獨立 critic；不要把 HTML 預覽當作語意證據，也不要在接受前寫入。",
    "capture_exceptions_propose_marker": "[提出首選表達]",
    "capture_copy_output_btn": "複製草稿輸出",
    "capture_copy_output_copied": "已複製草稿輸出。",
    "capture_copy_prompt_btn": "複製 AI 提示詞",
    "capture_copy_prompt_copied": "已複製 AI 提示詞。",
    "capture_result_title": "本機診斷預覽",
    "capture_empty": "貼上原文以複製 AI 檢視請求，或執行選用預覽。",
    "capture_none": "本機預覽未發現可能的例外。這不表示語意 AI 檢視已完成。",
    "capture_note": "僅供復原。本機預覽不能證明已理解對話；任何寫入前都應把完整原文交給 AI。",
    "capture_ready": "本機預覽發現可能需要檢視的項目。任何寫入前都應把完整原文交給 AI。",
    "capture_loaded": "「{term}」來自診斷預覽。儲存前請由 AI 驗證。",
    "capture_current_label": "（目前）",
    "capture_candidate1_label": "（首選）",
    "capture_candidate2_label": "（替代表達）",
    "capture_footer": "本機預覽僅供診斷；一般流程的決定由語意 AI 檢視負責。",
    "capture_keep_current": "保留目前表述",
    "capture_prompt_header": "請對下方準確原文執行已安裝的 VEIL capture。使用有證據的語意決定框架（contract v2）與獨立 critic，不要把 HTML 正規表示式預覽當作語意證據。自動結果保持靜默，僅將未解決的持久決定合併為一個問題。",
    "capture_prompt_footer": "使用準確的原文證據，保留已提供的首選表達，並在使用者接受合併決定前不要寫入任何規則。",
    "register_title": "登錄或修改規則",
    "advanced_options": "選用替代表達與復原命令",
    "field_term": "術語",
    "field_preferred": "首選表達",
    "field_alt2": "替代表達 1",
    "field_alt3": "替代表達 2",
    "register_term_placeholder": "例如: current state",
    "register_preferred_placeholder": "例如: present state",
    "register_alt2_placeholder": "可選替代項",
    "register_alt3_placeholder": "可選替代項",
    "register_btn": "複製儲存請求",
    "register_commands_btn": "進階：複製命令",
    "register_missing": "術語和首選表達為必填。",
    "register_copied": "已複製登錄請求。",
    "register_commands_copied": "已複製登錄命令。",
    "col_term": "術語",
    "col_preferred": "首選表達",
    "col_alt2": "替代表達 1",
    "col_alt3": "替代表達 2",
    "col_actions": "操作",
    "copy_btn": "複製",
    "delete_btn": "刪除",
    "copy_done": "已複製",
    "copy_manual": "無法使用剪貼簿。請手動複製以下文字：",
    "copy_manual_done": "已開啟手動複製提示。",
    "copy_failed": "複製失敗。請從提示中手動複製文字。",
    "count_registered": "已登錄 {n} 個術語",
    "count_matching": "符合 {n} 個術語",
    "copy_instruction": "將「{term}」改成「{candidate}」",
    "delete_instruction_header": "若要刪除此規則，請執行以下命令：",
    "delete_copied": "已複製刪除命令。",
    "register_instruction_header": "若要登錄此規則，請執行以下命令：",
    "register_prompt_header": "請在目前的儲存庫中登錄這條 VEIL 規則：",
    "register_prompt_footer": "更新 SQLite canonical，然後重新產生 mirror 和 veil.html。",
}

_HTML_UI_AR: dict[str, str] = {
    **_HTML_UI_EN,
    "lang": "ar",
    "title": "VEIL - قواعد المصطلحات",
    "search_placeholder": "ابحث في المصطلحات...",
    "instruction": "تعمل المراجعة المعتادة عند نهاية المهمة داخل Skill المثبت. هذه الصفحة للاسترداد فقط: انسخ النص الكامل لمراجعة دلالية بالذكاء الاصطناعي، أو شغّل التشخيص المحلي عند الحاجة. يمكن مراجعة القواعد المسجلة أو تغييرها أدناه.",
    "capture_title": "استرداد مراجعة الذكاء الاصطناعي",
    "capture_description": "الصق النص الأصلي وانسخ طلب مراجعة كاملًا واحدًا. المعاينة المحلية الاختيارية مبنية على التعبيرات النمطية وقد تفوّت القرارات أو تصنفها خطأً.",
    "capture_placeholder": "الصق النص الأصلي الدقيق للمراجعة...",
    "capture_btn": "تشغيل المعاينة التشخيصية المحلية",
    "capture_exceptions_copy_btn": "نسخ طلب مراجعة كامل للذكاء الاصطناعي",
    "capture_exceptions_copied": "تم نسخ طلب المراجعة الكامل.",
    "capture_exceptions_prompt_header": "شغّل VEIL capture المثبت على هذا النص الدقيق.",
    "capture_exceptions_prompt_footer": "استخدم عقد الإطارات الدلالية v2 ومراجعة critic مستقلة؛ لا تعتبر معاينة HTML دليلاً دلالياً ولا تكتب قبل القبول.",
    "capture_exceptions_propose_marker": "[اقتراح صيغة مفضلة]",
    "capture_copy_output_btn": "نسخ مخرجات المسودة",
    "capture_copy_output_copied": "تم نسخ مخرجات المسودة.",
    "capture_copy_prompt_btn": "نسخ موجّه الذكاء الاصطناعي",
    "capture_copy_prompt_copied": "تم نسخ موجّه الذكاء الاصطناعي.",
    "capture_result_title": "معاينة تشخيصية محلية",
    "capture_empty": "الصق النص لنسخ طلب مراجعة بالذكاء الاصطناعي أو لتشغيل المعاينة الاختيارية.",
    "capture_none": "لم تجد المعاينة المحلية استثناءً محتملاً. هذا لا يعني اكتمال المراجعة الدلالية.",
    "capture_note": "للاسترداد فقط. المعاينة المحلية ليست دليلاً على فهم المحادثة. أرسل النص الكامل إلى الذكاء الاصطناعي قبل أي كتابة.",
    "capture_ready": "وجدت المعاينة المحلية عناصر محتملة للمراجعة. أرسل النص الكامل إلى الذكاء الاصطناعي قبل أي كتابة.",
    "capture_loaded": "جاء «{term}» من المعاينة التشخيصية. تحقّق منه بالذكاء الاصطناعي قبل الحفظ.",
    "capture_current_label": " (الحالي)",
    "capture_candidate1_label": " (المفضلة)",
    "capture_candidate2_label": " (بديلة)",
    "capture_footer": "المعاينة المحلية للتشخيص فقط؛ والمراجعة الدلالية بالذكاء الاصطناعي هي صاحبة القرار في المسار المعتاد.",
    "capture_keep_current": "الإبقاء على الصياغة الحالية",
    "capture_prompt_header": "شغّل VEIL capture المثبت على النص الدقيق أدناه. استخدم إطارات قرار دلالية مدعومة بالأدلة (contract v2) ومراجعة critic مستقلة، ولا تستخدم معاينة HTML النمطية كدليل دلالي. أبقِ النتائج التلقائية صامتة واجمع القرارات الدائمة غير المحسومة في سؤال واحد فقط.",
    "capture_prompt_footer": "استخدم أدلة دقيقة من النص الأصلي، واحتفظ بالصيغ المفضلة المقدمة، ولا تكتب أي قاعدة حتى يقبل المستخدم القرار المجمّع.",
    "register_title": "تسجيل قاعدة أو تغييرها",
    "advanced_options": "البدائل الاختيارية وأوامر الاسترداد",
    "field_term": "المصطلح",
    "field_preferred": "الصيغة المفضلة",
    "field_alt2": "بديل 1",
    "field_alt3": "بديل 2",
    "register_term_placeholder": "مثال: current state",
    "register_preferred_placeholder": "مثال: present state",
    "register_alt2_placeholder": "بديل اختياري",
    "register_alt3_placeholder": "بديل اختياري",
    "register_btn": "نسخ طلب الحفظ",
    "register_commands_btn": "متقدم: نسخ الأوامر",
    "register_missing": "المصطلح والصيغة المفضلة مطلوبان.",
    "register_copied": "تم نسخ طلب التسجيل.",
    "register_commands_copied": "تم نسخ أوامر التسجيل.",
    "col_term": "المصطلح",
    "col_preferred": "الصيغة المفضلة",
    "col_alt2": "بديل 1",
    "col_alt3": "بديل 2",
    "col_actions": "الإجراءات",
    "copy_btn": "نسخ",
    "delete_btn": "حذف",
    "copy_done": "تم النسخ",
    "copy_manual": "تعذر الوصول إلى الحافظة. انسخ هذا النص يدوياً:",
    "copy_manual_done": "تم فتح نافذة النسخ اليدوي.",
    "copy_failed": "فشل النسخ. انسخ النص يدوياً من النافذة.",
    "count_registered": "تم تسجيل {n} مصطلحاً",
    "count_matching": "{n} مصطلحات مطابقة",
    "copy_instruction": "غيّر '{term}' إلى '{candidate}'",
    "delete_instruction_header": "نفّذ الأوامر التالية لحذف هذه القاعدة:",
    "delete_copied": "تم نسخ أوامر الحذف.",
    "register_instruction_header": "نفّذ الأوامر التالية لتسجيل هذه القاعدة:",
    "register_prompt_header": "سجّل قاعدة VEIL هذه في المستودع الحالي:",
    "register_prompt_footer": "حدّث SQLite canonical ثم أعد توليد mirror و veil.html.",
}

_HTML_UI_BY_LANG: dict[str, dict[str, str]] = {
    "en": _HTML_UI_EN,
    "ja": _HTML_UI_JA,
    "ko": _HTML_UI_KO,
    "zh-hans": _HTML_UI_ZH_HANS,
    "zh-hant": _HTML_UI_ZH_HANT,
    "ar": _HTML_UI_AR,
}


def get_html_ui_for_lang(lang: str | None) -> dict[str, str]:
    normalized = (lang or "en").strip().lower().replace("_", "-")
    if normalized.startswith("zh-cn") or normalized.startswith("zh-sg") or normalized == "zh":
        key = "zh-hans"
    elif normalized.startswith("zh-tw") or normalized.startswith("zh-hk") or normalized.startswith("zh-mo"):
        key = "zh-hant"
    elif normalized.startswith("ja"):
        key = "ja"
    elif normalized.startswith("ko"):
        key = "ko"
    elif normalized.startswith("ar"):
        key = "ar"
    else:
        key = "en"
    return dict(_HTML_UI_BY_LANG.get(key, _HTML_UI_EN))
