from __future__ import annotations

import re

LABEL_INDUSTRY_TERM = "industry_term"
LABEL_COINED_OR_SHORTENED = "coined_or_shortened"
LABEL_FILE_CONFIG_IDENTIFIER = "file_config_identifier"
LABEL_OTHER = "other"
LABEL_UNKNOWN = "unknown"

ALL_LABELS = (
    LABEL_INDUSTRY_TERM,
    LABEL_COINED_OR_SHORTENED,
    LABEL_FILE_CONFIG_IDENTIFIER,
    LABEL_OTHER,
    LABEL_UNKNOWN,
)

PROPER_NOUN_TERMS = {
    "adop",
    "aim",
    "aider",
    "anthropic",
    "bash",
    "copilot",
    "cursor",
    "dependabot",
    "gitleak",
    "github",
    "git hub",
    "javascript",
    "openai",
    "pier",
    "codex",
    "claude",
    "gemini",
    "mypy",
    "playwright",
    "powershell",
    "python",
    "pytest",
    "saiga",
    "symphony",
    "sqlite",
    "vault",
    "veil",
}

KNOWN_INDUSTRY_TERMS = {
    "adapter",
    "append only",
    "artifact",
    "assert",
    "audit",
    "backlog",
    "base url",
    "bootstrap",
    "branch",
    "branch protection",
    "bytecode",
    "collector",
    "commit",
    "console",
    "contract",
    "control plane",
    "checkpoint",
    "checkout",
    "composer",
    "continuous integration",
    "coordinator",
    "coverage",
    "coupling",
    "database",
    "dataset",
    "distribution",
    "drift",
    "engine",
    "endpoint",
    "execution",
    "fail close",
    "filesystem",
    "gate",
    "generator",
    "gitignored",
    "grep",
    "guardrail",
    "healthcheck",
    "hosted gate",
    "instrumentation",
    "lint",
    "linter",
    "hook",
    "kernel",
    "mainline",
    "master",
    "metadata",
    "migration",
    "mtime",
    "namespace",
    "normalize",
    "observer",
    "oauth",
    "orchestration",
    "playback",
    "protocol",
    "push",
    "readback",
    "read only",
    "regression",
    "release",
    "renderer",
    "reset",
    "regulation",
    "ruleset",
    "scan",
    "scanning",
    "scope",
    "screening",
    "secret",
    "security",
    "self describing",
    "seed",
    "schema",
    "shell",
    "step",
    "subagent",
    "sync",
    "token",
    "test",
    "timezone",
    "trigger",
    "triage",
    "untracked",
    "use case",
    "package",
    "packaging",
    "prompt",
    "runtime",
    "machine readable",
    "schema migration",
    "sync target",
    "tracked file",
    "validator",
    "workflow",
    "worktree",
    "writeback",
    "writer",
    "orchestrator",
    "stdin",
    "http",
}

KNOWN_INDUSTRY_ACRONYMS = {
    "api",
    "db",
    "html",
    "json",
    "ui",
    "ux",
}

KNOWN_REPO_DIR_TERMS = {
    "archive",
    "common",
    "docs",
    "folder",
    "generated",
    "governance",
    "index",
    "packet",
    "pycache",
    "spec",
    "template",
    "workspace",
}

KNOWN_FILE_CONFIG_TERMS = {
    "adop pytest",
    "adop pytest base2",
    "adop pytest cache",
    "analyze draft",
    "artifact shelf",
    "candidate intake note",
    "ci",
    "compatibility diagnosis",
    "config",
    "configuration",
    "decision owner",
    "file config identifier",
    "dashboard common scope summary",
    "data dashboard endpoint mode",
    "data dashboard selected environment",
    "data dashboard selected environment scope",
    "data dashboard selected project scope",
    "data dashboard selected tenant scope",
    "data environment mode",
    "data runtime surface id",
    "data selected environment",
    "data selected environment scope",
    "data selected project scope",
    "data selected tenant scope",
    "export html",
    "filter reason",
    "filter status",
    "guided path",
    "html path",
    "index local composed sample",
    "judgment reason",
    "judgment report",
    "landing target",
    "canonical body",
    "current task register",
    "manifest",
    "md",
    "next action",
    "preventive action",
    "generated sink",
    "gitignore",
    "project local",
    "project profile",
    "project oriented",
    "quick close trial",
    "quick compare",
    "quick trial",
    "readme",
    "declared vs observed",
    "draft output",
    "runtime artifact shelf",
    "runtime scope readback updated",
    "se",
    "start trial",
    "support docs",
    "system dev",
    "trial result",
    "trial packet",
    "url",
    "writeback target",
    "yaml",
}

SHORTENED_TERMS = {
    "repo",
    "repos",
    "repository",
}

GENERIC_SINGLE_WORDS = {
    "ai",
    "accepted",
    "acceptance",
    "active",
    "addendum",
    "aligned",
    "allowed",
    "architecture",
    "automatically",
    "closing",
    "adoption",
    "agent",
    "approval",
    "alert",
    "aggregate",
    "anchor",
    "apply",
    "asset",
    "basetemp",
    "block",
    "blocker",
    "blocking",
    "baseline",
    "backend",
    "benchmark",
    "breakdown",
    "bound",
    "brief",
    "bounded",
    "bridge",
    "board",
    "carrier",
    "category",
    "caution",
    "canon",
    "cache",
    "case",
    "capture",
    "candidate",
    "carried",
    "client",
    "change",
    "changes",
    "check",
    "cleaner",
    "claim",
    "class",
    "clear",
    "command",
    "comment",
    "community",
    "companion",
    "comparison",
    "completed",
    "cogitated",
    "compatibility",
    "consistency",
    "copy",
    "counted",
    "coupon",
    "condition",
    "coupled",
    "ctrl",
    "console",
    "core",
    "current",
    "canonical",
    "cleanup",
    "close",
    "code",
    "control",
    "content",
    "completion",
    "compliance",
    "context",
    "criteria",
    "data",
    "decision",
    "date",
    "dead",
    "desktop",
    "defense",
    "decide",
    "delegation",
    "deadline",
    "declaration",
    "debug",
    "defer",
    "detect",
    "decomposition",
    "delegated",
    "description",
    "detail",
    "design",
    "deletion",
    "disabled",
    "discovery",
    "diagnosis",
    "diff",
    "direct",
    "daily",
    "dispatch",
    "document",
    "done",
    "domain",
    "downstream",
    "directly",
    "driven",
    "dynamic",
    "environment",
    "coding",
    "dual",
    "feed",
    "evidence",
    "entry",
    "enforcement",
    "english",
    "empty",
    "enough",
    "escalation",
    "exact",
    "expected",
    "evaluator",
    "error",
    "explore",
    "expand",
    "export",
    "exit",
    "fallback",
    "failure",
    "fail",
    "file",
    "files",
    "final",
    "filename",
    "finding",
    "family",
    "future",
    "fixed",
    "fixture",
    "filter",
    "first",
    "flow",
    "field",
    "framework",
    "frozen",
    "full",
    "green",
    "generic",
    "glossary",
    "grouped",
    "guard",
    "guide",
    "guidance",
    "guided",
    "hardening",
    "heading",
    "helper",
    "harness",
    "hidden",
    "historical",
    "hosted",
    "hold",
    "expiry",
    "import",
    "imported",
    "inspection",
    "inventory",
    "injection",
    "input",
    "indexcurrent",
    "issue",
    "human",
    "immediately",
    "implementation",
    "indirect",
    "insight",
    "intake",
    "investigation",
    "acceptable",
    "launch",
    "line",
    "label",
    "last",
    "large",
    "legacy",
    "launcher",
    "latest",
    "level",
    "link",
    "live",
    "living",
    "localhost",
    "list",
    "limit",
    "lookup",
    "local",
    "loop",
    "manage",
    "managed",
    "manager",
    "maintainer",
    "match",
    "manual",
    "material",
    "matrix",
    "mechanism",
    "medium",
    "marker",
    "mention",
    "message",
    "memory",
    "mismatch",
    "missing",
    "mirror",
    "mock",
    "mode",
    "maintenance",
    "minimum",
    "mojibake",
    "mutation",
    "multiple",
    "multiword",
    "narrow",
    "naturalness",
    "naming",
    "next",
    "nested",
    "noun",
    "open",
    "output",
    "overlay",
    "ordinary",
    "operator",
    "operational",
    "operation",
    "only",
    "order",
    "overall",
    "ownership",
    "owner",
    "pass",
    "passed",
    "parse",
    "path",
    "pattern",
    "pending",
    "phase",
    "placement",
    "plane",
    "policy",
    "parked",
    "partial",
    "payload",
    "platform",
    "philosophy",
    "placeholder",
    "point",
    "principle",
    "practical",
    "private",
    "proposed",
    "preset",
    "probe",
    "proof",
    "prefix",
    "preventive",
    "primary",
    "process",
    "profile",
    "projection",
    "promote",
    "proper",
    "preview",
    "product",
    "project",
    "projects",
    "promotion",
    "public",
    "question",
    "quality",
    "quoting",
    "quick",
    "quickstart",
    "recent",
    "recommended",
    "recorded",
    "recording",
    "record",
    "reference",
    "register",
    "registration",
    "reader",
    "readability",
    "reading",
    "readiness",
    "rate",
    "required",
    "remote",
    "need",
    "needed",
    "necessary",
    "reachability",
    "reason",
    "shortcut",
    "unresolved",
    "resolved",
    "result",
    "rename",
    "reject",
    "residual",
    "residue",
    "resume",
    "retired",
    "review",
    "reopen",
    "reopened",
    "reusable",
    "ribbon",
    "reroute",
    "rerun",
    "risk",
    "role",
    "routing",
    "runner",
    "root",
    "route",
    "rule",
    "rulebook",
    "rules",
    "clean",
    "confusing",
    "dirty",
    "bare",
    "batch",
    "safe",
    "stale",
    "scale",
    "searched",
    "section",
    "standard",
    "slice",
    "state",
    "stage",
    "status",
    "submit",
    "support",
    "surface",
    "shared",
    "shelf",
    "sink",
    "snapshot",
    "source",
    "spoken",
    "setup",
    "shelve",
    "split",
    "still",
    "stop",
    "structure",
    "suffix",
    "summary",
    "success",
    "sample",
    "safety",
    "signal",
    "skill",
    "selected",
    "selection",
    "silent",
    "side",
    "scratch",
    "script",
    "secondary",
    "server",
    "semantic",
    "session",
    "step4",
    "stable",
    "static",
    "stub",
    "text",
    "type",
    "target",
    "targeted",
    "task",
    "tenant",
    "tail",
    "ticket",
    "topic",
    "table",
    "taxonomy",
    "team",
    "thematic",
    "then",
    "term",
    "terms",
    "theme",
    "this",
    "short",
    "runs",
    "sweep",
    "tool",
    "transfer",
    "transcript",
    "treat",
    "truth",
    "unrelated",
    "unknown",
    "update",
    "upper",
    "user",
    "users",
    "purpose",
    "version",
    "verdict",
    "visible",
    "violation",
    "warning",
    "warn",
    "when",
    "where",
    "window",
    "worker",
    "work",
    "wrote",
    "wording",
    "write",
    "wiring",
    "usage",
    "what",
    "with",
    "without",
    "would",
    "writable",
    "conversation",
    "cost",
    "couple",
    "credential",
    "declared",
    "fork",
    "item",
    "license",
    "name",
    "optional",
    "high",
    "best",
    "closure",
    "blocked",
    "hygiene",
    "carry",
    "handoff",
    "bigram",
    "other",
    "queue",
    "read",
    "request",
    "judgment",
    "body",
    "boundary",
    "caller",
    "checklist",
    "closed",
    "bundle",
    "broken",
    "creation",
    "creating",
    "cannot",
    "confirmed",
    "critical",
    "crossref",
    "delete",
    "disposition",
    "edit",
    "evaluation",
    "example",
    "expanded",
    "feature",
    "fragmentation",
    "forbidden",
    "hash",
    "here",
    "hint",
    "management",
    "model",
    "node",
    "none",
    "overview",
    "production",
    "protection",
    "prerequisite",
    "requirement",
    "return",
    "section",
    "setting",
    "software",
    "standalone",
    "synthetic",
    "trial",
    "tree",
    "validation",
    "verification",
    "verify",
    "viewer",
    "whitelist",
    "scene",
    "integrity",
    "experiment",
    "absence",
    "authority",
    "autonomous",
    "living",
    "lane",
    "layer",
    "goal",
    "action",
    "keep",
    "known",
    "reviewer",
    "auditor",
    "engineer",
    "start",
    "acceptable",
    "build",
    "delete",
    "execute",
    "ceremony",
    "hedge",
    "bump",
    "chore",
    "clone",
    "count",
    "deferred",
    "deps",
    "draft",
    "evaluated",
    "from",
    "host",
    "install",
    "note",
    "publication",
    "report",
    "same",
    "terminal",
    "validate",
    "verified",
    "waiver",
    "inside",
    "below",
    "used",
    "external",
    "under",
    "another",
    "corresponding",
    "belong",
    "that",
    "approved",
    "consuming",
    "distributed",
    "editable",
    "planned",
    "intended",
    "once",
    "reserved",
    "maps",
    "reach",
    "they",
    "packaged",
    "layout",
    "variant",
    "define",
    "general",
    "move",
    "restore",
    "anything",
    "such",
    "replace",
    "restart",
    "tracking",
    "time",
    "understanding",
    "contain",
    "each",
    "named",
    "child",
    "official",
    "over",
    "completeness",
    "into",
    "rewrite",
    "assumption",
    "authorization",
    "bearer",
    "originator",
    "credit",
    "inspector",
    "epoch",
    "effective",
    "earliest",
    "expire",
    "afrayde01",
    "unit",
    "smoke",
    "publish",
    "about",
    "contribution",
    "waive",
    "tier",
    "sandbox",
    "connector",
    "default",
    "main",
    "classic",
    "form",
    "markdown",
    "head",
    "visibility",
    "picker",
    "impression",
    "mentioned",
    "saiganakato",
    "image",
    "author",
    "history",
    "global",
    "override",
    "committer",
    "accessible",
    "banked",
    "referral",
    "invite",
    "undocumented",
    "cookie",
    "releas",
    "generate",
    "arbitrary",
    "composition",
    "method",
    "catalog",
    "generation",
    "pack",
    "validated",
    "omit",
    "creative",
    "strategic",
    "wait",
    "absolute",
    "actual",
    "experimental",
    "verge",
    "developer",
    "aidev",
    "agentic",
    "much",
    "star",
    "configuring",
    "advanced",
    "evaluating",
    "median",
    "impact",
    "popular",
    "smell",
    "president",
    "gathering",
    "structured",
    "dogfood",
    "judge",
    "reflection",
    "dogfooding",
    "typo",
    "stay",
    "remain",
    "should",
    "also",
    "format",
    "archetype",
    "custom",
    "research",
    "repeat",
    "invocation",
    "constitution",
    "access",
    "acronym",
    "added",
    "adding",
    "adopt",
    "adoptable",
    "against",
    "already",
    "analyze",
    "analyzer",
    "applying",
    "around",
    "assistant",
    "attachment",
    "awkward",
    "back",
    "before",
    "blow",
    "both",
    "broad",
    "broader",
    "came",
    "candidate1",
    "cas",
    "chat",
    "checked",
    "checking",
    "classification",
    "classified",
    "classifier",
    "classify",
    "cleanly",
    "closer",
    "coined",
    "composed",
    "concrete",
    "confirm",
    "consistent",
    "corpus",
    "currently",
    "dashboard",
    "deciding",
    "decoded",
    "denied",
    "detector",
    "didn",
    "directory",
    "does",
    "doing",
    "drop",
    "dropped",
    "e5981",
    "either",
    "embedded",
    "encoding",
    "entrypoint",
    "exactly",
    "expectation",
    "explain",
    "explicit",
    "extract",
    "extracting",
    "extraction",
    "extractor",
    "fake",
    "fall",
    "fenced",
    "focused",
    "found",
    "fragment",
    "handling",
    "handover",
    "healthy",
    "industry",
    "inline",
    "interesting",
    "internally",
    "join",
    "kind",
    "know",
    "landing",
    "left",
    "like",
    "likely",
    "locale",
    "lock",
    "logic",
    "look",
    "looking",
    "making",
    "meaningful",
    "mechanical",
    "misclassification",
    "more",
    "most",
    "mostly",
    "noise",
    "noisy",
    "nothing",
    "observed",
    "oriented",
    "outside",
    "part",
    "pasted",
    "patch",
    "patching",
    "phrase",
    "pick",
    "polishing",
    "present",
    "protected",
    "pulling",
    "rather",
    "real",
    "registered",
    "related",
    "remained",
    "remaining",
    "resolve",
    "right",
    "ripple",
    "running",
    "safer",
    "sanitiz",
    "sanitization",
    "scoped",
    "scoring",
    "segment",
    "shed",
    "single",
    "skeleton",
    "small",
    "smallest",
    "specialist",
    "stepping",
    "store",
    "suite",
    "surfaced",
    "system",
    "than",
    "there",
    "through",
    "together",
    "tracing",
    "true",
    "turn",
    "tweak",
    "unexpected",
    "unlink",
    "untouched",
    "updated",
    "value",
    "warned",
    "whether",
    "which",
    "while",
    "word",
}

PHRASE_WEAK_TOKENS = {
    "a",
    "an",
    "and",
    "for",
    "in",
    "of",
    "on",
    "or",
    "the",
    "to",
}

COINED_HEAD_TOKENS = {
    "clutter",
    "file",
    "files",
    "packaging",
    "policy",
    "support",
}

KNOWN_COINED_TERMS = {
    "accepted route",
    "bounded naturalness",
    "carry forward",
    "current state",
    "dev only",
    "developer support",
    "github standard",
    "maintainer only",
    "maintainer only file",
    "manager copy",
    "non current",
    "owner only",
    "punctuation triple",
    "proof blocker",
    "repo truth",
    "root clutter",
    "unstable wording",
    "veil capture",
    "writable shelf",
}

KNOWN_OTHER_MULTIWORD_TERMS = {
    "branch question",
    "current route",
    "current checkpoint",
    "current surface",
    "current issue",
    "execution lane",
    "failing test",
    "launch evidence",
    "live state",
    "operator view",
    "parse failure",
    "preferred term",
    "read surface",
    "repo hygiene",
    "shelf class",
    "source term",
    "task register",
}

ADOPTABLE_OTHER_MULTIWORD_TERMS = {
    "branch question",
    "current route",
    "current checkpoint",
    "current surface",
    "execution lane",
    "launch evidence",
    "live state",
    "operator view",
    "parse failure",
    "read surface",
    "repo hygiene",
    "shelf class",
    "task register",
}

PREVIEWABLE_GENERIC_SINGLE_TERMS = {
    "adoptable",
    "candidate",
    "passed",
    "polishing",
    "preview",
    "status",
}

IDENTIFIER_TOKEN_PATTERN = (
    r"(?<![A-Za-z0-9_])(?:"
    r"/[A-Za-z0-9_.-]+(?:/[A-Za-z0-9_.-]+)?"
    r"|"
    r"[A-Za-z0-9_.-]+/[A-Za-z0-9_./*-]+"
    r"|[A-Za-z0-9_.-]*\*\*?(?:/[A-Za-z0-9_.-]+)?"
    r"|[A-Za-z0-9_.-]+\.[A-Za-z0-9_.-]+"
    r"|[A-Za-z0-9]+_[A-Za-z0-9_.-]+"
    r"|[0-9a-fA-F]{7,40}"
    r"|[A-Z]{2,}"
    r")(?![A-Za-z0-9_])"
)
WORD_TOKEN_PATTERN = r"[A-Za-z][A-Za-z0-9-]*"

IDENTIFIER_TOKEN_RE = re.compile(IDENTIFIER_TOKEN_PATTERN)
WORD_TOKEN_RE = re.compile(WORD_TOKEN_PATTERN)


def capture_taxonomy_payload() -> dict[str, object]:
    return {
        "labels": {
            "industry_term": LABEL_INDUSTRY_TERM,
            "coined_or_shortened": LABEL_COINED_OR_SHORTENED,
            "file_config_identifier": LABEL_FILE_CONFIG_IDENTIFIER,
            "other": LABEL_OTHER,
            "unknown": LABEL_UNKNOWN,
        },
        "proper_noun_terms": sorted(PROPER_NOUN_TERMS),
        "known_industry_terms": sorted(KNOWN_INDUSTRY_TERMS),
        "known_industry_acronyms": sorted(KNOWN_INDUSTRY_ACRONYMS),
        "known_repo_dir_terms": sorted(KNOWN_REPO_DIR_TERMS),
        "known_file_config_terms": sorted(KNOWN_FILE_CONFIG_TERMS),
        "shortened_terms": sorted(SHORTENED_TERMS),
        "generic_single_words": sorted(GENERIC_SINGLE_WORDS),
        "phrase_weak_tokens": sorted(PHRASE_WEAK_TOKENS),
        "coined_head_tokens": sorted(COINED_HEAD_TOKENS),
        "known_coined_terms": sorted(KNOWN_COINED_TERMS),
        "known_other_multiword_terms": sorted(KNOWN_OTHER_MULTIWORD_TERMS),
        "adoptable_other_multiword_terms": sorted(ADOPTABLE_OTHER_MULTIWORD_TERMS),
        "previewable_generic_single_terms": sorted(PREVIEWABLE_GENERIC_SINGLE_TERMS),
        "identifier_token_pattern": IDENTIFIER_TOKEN_PATTERN,
        "word_token_pattern": WORD_TOKEN_PATTERN,
    }
